### ISSUE TITLE
Logging of tables

### ISSUE THREAD

**Issue by finsberg** [justinlaughlin/stubs#108]
Tables in are not rendered as expected when logged (see e.g https://rangamanilabucsd.github.io/smart/examples/example3/example3.html and screenshot).

![Screenshot 2023-05-31 at 21 31 52](https://github.com/RangamaniLabUCSD/smart/assets/2010323/7db4cbf3-3c61-4a68-b23a-e331b86d1889)

One way to fix this is to add a newline after logging the level. However, we probably don't want to make this the default behaviour, so it would perhaps make sense to add a new `FormatType` for table (e.g in https://github.com/RangamaniLabUCSD/smart/blob/97ad37992f8cf07d5ee53fbb1491adfc0712b6e6/smart/config.py#L36)

**Comment by emmetfrancis** [comment]
Agreed, would you be able to implement this? If not, I can take a look tomorrow.

**Comment by finsberg** [comment]
> Agreed, would you be able to implement this? If not, I can take a look tomorrow.

I can take a look at this today
