### ISSUE TITLE
`filler_char` in logs

### ISSUE THREAD

**Issue by finsberg** [justinlaughlin/stubs#109]
For some reason, the logs for warnings starts with `....` (see https://rangamanilabucsd.github.io/smart/examples/example3/example3.html and screenshot)

![Screenshot 2023-05-31 at 21 35 49](https://github.com/RangamaniLabUCSD/smart/assets/2010323/7d8c841a-aa25-46ab-9ef9-11b5a59a45f9)

I guess this is related to the `filler_char` in https://github.com/RangamaniLabUCSD/smart/blob/97ad37992f8cf07d5ee53fbb1491adfc0712b6e6/smart/config.py#LL132C18-L132C18

Is this something we want?

**Comment by emmetfrancis** [comment]
I am on board with removing the filler_char
