### ISSUE TITLE
[JOSS Review] Installation

### ISSUE THREAD

**Issue by mbarzegary** [justinlaughlin/stubs#118]
Dear authors,

The software installation routine is straightforward, and there is no special issue with it. However, I found the package a bit difficult to get started with, especially for a normal user. If the package is supposed to be used by advanced users only (which I think is not), it should be explicitly mentioned. 

* After the installation using the docker approach, how is the user supposed to work with the examples? I think there is no way in the current setup. Jupyter is not installed in the docker image, and there is no port forwarding on the docker run command. I would say a non-advanced user can never find out how to do that, so it can be beneficial to guide the users on how to run the example codes and see how the library works in action. I did it by running `jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root` inside the container (after forwarding the port in the docker execution command), in which the inline PyVista visualization didn't still work (which is because PyVista is not installed inside the container). 
* As a follow-up to the above point, it can be nice if the user can have access to the example codes in separate files without the Jupyter notebooks, similar to example 3. These codes (accompanied by some documentation on how to run them) can show a normal user how to use the package after the installation.

P.S. This issue is related to https://github.com/openjournals/joss-reviews/issues/5580

**Comment by jorgensd** [comment]
@mbarzegary I've tried to address the comments above in the #123.

Some notes:
- The PR changes the base image to have `jupyter`, `jupyterlab` and other dependencies
  - On linux with ARM build, VTK does not ship binaries, so we cannot build `pyvista` on that platform (as the build time exceeds the Github CI runtime). Thus only `linux/amd64` images will have pyvista.
- A separate image will be pushed to the Github Registries, which uses `jupyter lab` as entrypoint, with the necessary arguments.
- The source code of smart is now located in `/repo` in the container, which is the default working directory if not overloaded by a user at container initialization.
