### ISSUE TITLE
 [JOSS Review] Reproducibility and functionality

### ISSUE THREAD

**Issue by mbarzegary** [justinlaughlin/stubs#119]
Dear authors,

Generally speaking, the software runs as described in the documentation. However, there are very minor comments in this regard:

* The software claims to be high-performance, but no performance test is reported. Having a small test on example 3 (as the relevant example on parallelization) can be nice in this regard.
* Is there any way to reproduce Figure 1 of the paper? Example 2 performs the simulation on the mentioned model on a simple geometry.

P.S. This issue is related to https://github.com/openjournals/joss-reviews/issues/5580

**Comment by emmetfrancis** [comment]
We now have introduced a version of Example 2 in 3D (as shown in Figure 1), which is included in our online documentation as well. We are in the process of considering possible performance tests that could be added.

**Comment by emmetfrancis** [comment]
Performance testing will be revisited upon future development of parallelization features
