### ISSUE TITLE
[JOSS REVIEW] Struggling with docker installation

### ISSUE THREAD

**Issue by oalii** [justinlaughlin/stubs#126]
Dear Authors,

As I am not a docker user, I am the perfect beta tester for your installation instructions. And unfortunately, trying to install and run the docker image I ran into similar difficulties as  @mbarzegary. 
FYI I am working on a Mac M1Pro and installed docker from the dmg file (I mention it as I don't know how os/machine-specific these issues can be).
I noticed that neither `Jupyter notebook` nor `pyvista` were initially present in your docker image.
With the help of an engineer from my team, ended up running the following custom CLI instruction: 

```docker run --rm -v $(pwd):/home/shared -w /home/shared -p 8889:8889 ghcr.io/rangamanilabucsd/smart:latest bash -c 'python3 -m pip install notebook pyvista && jupyter notebook --no-browser --ip 0.0.0.0 --port 8889 --allow-root'```

But somehow couldn't make it run...

As I said, I am not a docker power user  so the problem might be on my side. In this case, you might want to add more details in the installation procedures.

Could you fix this, so I can test the notebooks ?
Thx a lot !

**Comment by finsberg** [comment]
Thanks @oalii for taking the time to review this. It is really helpful for us to get feedback from someone that is not a docker power user.
We created a separate image with `jupyter` and `pyvista`, and you should be able to run it using the command
```
docker run -ti -p 8888:8888 --rm ghcr.io/rangamanilabucsd/smart-lab:latest
```

**Comment by finsberg** [comment]
And if you are already using port 8888 on your own laptop, you can forward the port to e.g 8889 as follows
```
docker run -ti -p 8889:8888 --rm ghcr.io/rangamanilabucsd/smart-lab:latest
```

**Comment by oalii** [comment]
Thanks a lot @finsberg ,
The new image is working just fine.
I will check the notebooks now.

**Comment by finsberg** [comment]
@oalii I am closing this now. Feel free to reopen it the issue remains.
