### ISSUE TITLE
Report parameters that are unused in a model

### ISSUE THREAD

**Issue by ctlee** [justinlaughlin/stubs#21]
It could possibly be a useful feature to report parameters that are unused by any model. At the least, it could reduce the database size. This could be useful if folks eventually develop databases of reactions and try to combine/merge them.

**Comment by justinlaughlin** [comment]
Implemented in e462e0267ea05a1acad6875f70dd5d095ebca8df . Default is to not allow unused parameters/species/compartments but this can be changed in config.flags
