### ISSUE TITLE
Add Time-dependent Parameters to SBML Converter

### ISSUE THREAD

**Issue by willxu1234** [justinlaughlin/stubs#27]
Eventually, we want to explore the possibility of converting our models that have time-dependent parameters to SBML. This doesn't seem to be supported yet, and we have to be able to convert both functions and CSV files to SBML.

One possibility we can explore is using Rules ([see the spec here](http://co.mbine.org/specifications/sbml.level-2.version-5.release-1.pdf#page=58&zoom=100,96,372)) to express our equations and define time as a standalone parameter, but this should be saved for after we have our base SBML capabilities in place.

Of course, native support is always preferred, and Chris suggested raising an issue to the SBML team to see if they can add support if we can instead of doing some workaround.

**Comment by justinlaughlin** [comment]
Prioritizing SBML -> STUBS rather than vice-versa
