### ISSUE TITLE
Documentation backend

### ISSUE THREAD

**Issue by jorgensd** [justinlaughlin/stubs#52]
Currently, this project is using readthedocs as a backend for its documentation. 
If we want a tighter integration with Github, we could use JupyterBook, as for instance done for 
https://github.com/ComputationalPhysiology/simcardems
https://computationalphysiology.github.io/simcardems/
and 
https://github.com/jorgensd/dolfinx-tutorial
https://jsdokken.com/dolfinx-tutorial/

It makes it easier to test locally. @emmetfrancis @justinlaughlin @finsberg any thoughts?

**Comment by jorgensd** [comment]
readthedocs supports conda config files, which is a bit tricky for this project, as it should preferably use the master branch of dolfin, which is not on conda-forge.

With jupyter-book, we would use the github actions to publish the package, and would therefore be able to use any docker image, for instance: ` docker pull ghcr.io/scientificcomputing/fenics:2023-01-16` which is FEniCS master branch built on Ubuntu 22.04 two days ago.

**Comment by finsberg** [comment]
I think moving away from readthedocs would be best. By using github pages we have more control over  the environment. The only downside as I can see is that we lose versioning of the pages, i.e that you can have different pages for different versions of the software, but I don't think this is relevant it our case.

**Comment by ctlee** [comment]
We've transitioned to Github Actions and pages for other projects in the lab. See Mem3DG as an example. We also added some first pass attempts to deploy documentation for multiple versions of docs. Only challenge is ensuring that fetched libraries and outgoing links remain live. 

https://github.com/RangamaniLabUCSD/Mem3DG/blob/master/.github/workflows/doc_versioning.yaml
https://rangamanilabucsd.github.io/Mem3DG/

**Comment by jorgensd** [comment]
> We've transitioned to Github Actions and pages for other projects in the lab. See Mem3DG as an example. We also added some first pass attempts to deploy documentation for multiple versions of docs. Only challenge is ensuring that fetched libraries and outgoing links remain live.
> 
> https://github.com/RangamaniLabUCSD/Mem3DG/blob/master/.github/workflows/doc_versioning.yaml https://rangamanilabucsd.github.io/Mem3DG/

For now I'm not sure having multiple versions of the documentation should be a priority. Eventually, we could do this through jupyter-book and `readthedocs` once we have a conda package for the latest dolfin commit.

The most important thing now is to have something on the documentation at all. The current webpage: https://stubs.readthedocs.io/en/development/ does not have any info on it, does not build, and the API does currently not show due to the aforementioned conda issues.

**Comment by ctlee** [comment]
> For now I'm not sure having multiple versions of the documentation should be a priority. Eventually, we could do this through jupyter-book and readthedocs once we have a conda package for the latest dolfin commit.

Multiple versions of docs is low priority. We could consider it more if there are major API changes between versions or when there are manuscripts with code published. Folks can always build their own docs from an archived version of a package. 

> The most important thing now is to have something on the documentation at all. The current webpage: https://stubs.readthedocs.io/en/development/ does not have any info on it, does not build, and the API does currently not show due to the aforementioned conda issues.

I agree.
