### ISSUE TITLE
Write joss paper

### ISSUE THREAD

**Issue by finsberg** [justinlaughlin/stubs#67]
Before we can submit the package to joss we need to write the [software paper](https://joss.readthedocs.io/en/latest/review_checklist.html#software-paper). I think the material in the overleaf document is more than enough, but we need to convert it to the correct format.

**Comment by meg-simula** [comment]
Agree, assigning myself to write a draft. Will ask @emmetfrancis for review in due time.

**Comment by meg-simula** [comment]
I've started this based on your write-up @emmetfrancis. Would you have a look at joss-paper/paper.md in this branch? I think you or perhaps Padmini have a better overview of existing tools, their pros/cons and the pros of STUBS/SMART than I do. Would also be nice to add some references and some figures (e.g. one idealized from a demo, one non-trivial from the Purkinjie network) to the file I think.

**Comment by meg-simula** [comment]
We could have added a bit of math, but consider that the JOSS paper should be between 250 and 1000 words (we are currently at around 600), I suggest we put this in the documentation instead (where it is much more valuable).

**Comment by emmetfrancis** [comment]
Thanks for starting this, Marie! I'll plan to add some suggested changes/additions before our meeting on Monday.
