### ISSUE TITLE
Add logging based on the python `logging` module

### ISSUE THREAD

**Issue by finsberg** [justinlaughlin/stubs#81]
Currently `stubs` uses the [`fancy_print`](https://github.com/RangamaniLabUCSD/stubs/blob/development/stubs/common.py#L247) function to log everything. This is essentially a wrapper around the print function for creating coloured output as well as some options for adding new lines and titles. You can also provide a filename in order to dump the output to a file.

The drawback with using this is that there is now way to customise the amount of data that is logged. This is usually done using a logger which provides a way to log information at different log levels (see e.g https://realpython.com/python-logging/ for a gentle introduction).

I have now been looking into how we can swap out the `fancy_print` function with proper logging using the `logging` module, but before implementing it I would like to get some feedback on it. 

The loggers in the `logging` module consists of handlers (e.g whether you want output to a file or to the console), and each handler has a formatter where you can customise the way the output is logged. 

Consider the following example where I try to use a custom formatter to mimic some of the features from the `fancy_print` function

```python
import logging
import dolfin
from termcolor import colored
from stubs.common import _fancy_print as fancy_print

comm = dolfin.MPI.comm_world
rank = comm.rank
size = comm.size

base_format = (
    "%(asctime)s %(rank)s%(name)s - %(levelname)s %(message)s (%(filename)s:%(lineno)d)"
)

class StubsFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:

        record.rank = f"CPU {rank}: " if size > 1 else ""
        format_type = getattr(record, "format_type", "default")
        if format_type == "title":
            record.msg = f" {record.msg} ".center(40, "=")
        color = getattr(record, "color", "white")
        log_fmt = colored(base_format, color)
        formatter = logging.Formatter(log_fmt)

        out = formatter.format(record)

        new_lines = getattr(record, "new_lines", (0, 0))
        prefix = "\n" * new_lines[0]
        postfix = "\n" * new_lines[1]
        return prefix + out + postfix



stream_handler = logging.StreamHandler()
stream_handler.setFormatter(StubsFormatter())

file_handler = logging.FileHandler("file.log")
file_handler.setFormatter(StubsFormatter())

logger = logging.getLogger(__name__)
logger.addHandler(stream_handler)
logger.addHandler(file_handler)

logger.setLevel(logging.DEBUG)


logger.info("Base text with logger")
fancy_print("Base text with fancy_print")

logger.info("Logger with color", extra=dict(color="magenta"))
fancy_print("Fancy with color", text_color="magenta")

logger.info("Title text with logger", extra=dict(format_type="title"))
fancy_print("Title text with fancy_print", format_type="title")

logger.info("Base text with logger with newline before", extra=dict(new_lines=(1, 0)))
fancy_print("Base text with fancy_print with newline before", new_lines=(1, 0))
```
Here I am creating two different handlers, one that outputs the logs to a file called `file.log` and one that output the same logs to the console. Both of these handlers gets a custom formatter which will mimic the `fancy_print` function. The custom formatter class (`StubsFormatter`)  has a method called `format` which are called automatically when you log a message and which operates on an object of type `LogRecord`. You can pass extra arguments to this `LogRecord` object using the `extra` keyword argument which is one way that we could pass on information about how the message should be logged.

Currently I have implemented a way to add a color (using `termcolor` which is currently used in `fancy_print`), adding new lines before and after the message and creating a title by adding `=` on both sides of the text. I also added the CPU rank in case we are running on multiple processes. 

Would be great to get some feedback on whether this is a good solution or not, or if you have any other suggestions?

**Comment by jorgensd** [comment]
I'm fine with suggestion implementation.

**Comment by emmetfrancis** [comment]
This looks great to me; I have no experience with the logging module, but it definitely makes sense to have the different levels to save. I think the current color settings and such from that Justin selected in fancy_print look nice, I suppose we could mimic the additional color choices by using "format_type" as an "extra" keyword argument. Is it possible we might want to implement additional logging levels, or do we think the default "debug, info, warning, error, critical" are sufficient?

**Comment by jorgensd** [comment]
> This looks great to me; I have no experience with the logging module, but it definitely makes sense to have the different levels to save. I think the current color settings and such from that Justin selected in fancy_print look nice, I suppose we could mimic the additional color choices by using "format_type" as an "extra" keyword argument. Is it possible we might want to implement additional logging levels, or do we think the default "debug, info, warning, error, critical" are sufficient?

I would say usually it is enough with 5 log-levels.

**Comment by emmetfrancis** [comment]
With the updated logging, is there a recommended way to add a file handler to the loggers? As is, when any script imports the SMART modules, a logger is initiated in each submodule (i.e. smart.model, smart.mesh, etc.) with the default settings initiated in smart.config. But as far as I can tell, there isn't a good way to add a file handler to all loggers after the initial imports (previously, the logging could be written to a file by using smart.config.global_settings["log_filename"]). 

I played around with a couple strategies to set a log file name in smart.config, but the main issue for me right now is that it can't be easily synchronized across all the loggers. Should a log file name be specified prior to imports, perhaps? Any ideas would be appreciated.

**Comment by finsberg** [comment]
The way you do this with the logging module is as follows
```python
import logging
import smart

logger = logging.getLogger("smart")
file_handler = logging.FileHandler("filename.log")
file_handler.setFormatter(logging.Formatter(smart.config.base_format))
logger.addHandler(file_handler)
```
If you want, I can update one of the examples to log to file?

We could also make it possible to still set the logging filename in the `global_settings`. Then we could just add the same code somewhere during initialisation. Not sure which place that would be best suited for this, perhaps in the `Model` initialization?
