### ISSUE TITLE
Rename STUBS 

### ISSUE THREAD

**Issue by meg-simula** [justinlaughlin/stubs#83]
Alternative names for stubs has been suggested. One alternative is

   Spatial Modelling Algorithms for Reaction-Transport [systems|models|equations]

with the acronym SMART. We need to

- [ ] agree on an updated name and acronym
- [ ] update the name in the file tree and documentation

Would be good to do this sooner rather than later. @emmetfrancis Are you all settled on the name SMART?

**Comment by emmetfrancis** [comment]
I think we are all on board for the name SMART at this point, and the code is in a relatively good place to do so now that unused sections of the code have been removed. If @jorgensd and @finsberg are on board, we can move forward with the name change next week.
