### ISSUE TITLE
Usage of MixedAssemblerTemp.*

### ISSUE THREAD

**Issue by jorgensd** [justinlaughlin/stubs#85]
The code is currently unused
https://github.com/search?q=repo%3ARangamaniLabUCSD%2Fsmart%20MixedAssemblerTemp&type=code

@emmetfrancis  do you know if it is still needed?
The reason (according to the comments) was:
> # Our custom assembler (something about dolfin's init_global_tensor was not
        # correct so we manually initialize the petsc matrix and then wrap with dolfin)
        # This assembly routine is the exact same as d.assemble_mixed() except
        # init_global_tensor() is commented out
        # Thanks to Prof. Kamensky and his student for the idea
        # https://github.com/hanzhao2020/PENGoLINS/blob/main/PENGoLINS/cpp/transfer_matrix.cpp

**Comment by emmetfrancis** [comment]
Good question, not needed from my standpoint, but perhaps we can check with Justin to see if there is something we should keep in mind for this assembler. @justinlaughlin, if you have a chance, do you recall what the issue was with the tensor assembly here?

**Comment by emmetfrancis** [comment]
From our conversation today, it sounds like we are safe to remove this C++ code at this point.
