### ISSUE TITLE
Enable use of MPI to run multiple simulations in parallel

### ISSUE THREAD

**Issue by emmetfrancis** [justinlaughlin/stubs#94]
Currently, this feature (see https://github.com/RangamaniLabUCSD/smart/tree/emmetfrancis/multimesh-mpi) only works if every process runs the same number of tasks (for instance, if running 10 conditions, needs to be subdivided into either 1, 2, 5, or 10 processes). Essentially, at the start of each task, the process will hang at dolfin.assemble_mixed within the function, "init_petsc_matnest" inside of smart.solvers until each process reaches that same point, then proceed.

Ideally, we should be able to run any number of processes in parallel as long as we are using the "MPI_SELF" communicator for the mesh and solver, but something within dolfin.assemble_mixed seems to prevent this. As an example that currently fails, consider running "example3_multimeshMPI" (https://github.com/RangamaniLabUCSD/smart/blob/emmetfrancis/multimesh-mpi/examples/example3/example3_multimeshMPI.py) as:

`mpiexec -np 3 python3 example3_multimeshMPI.py`

The code section of interest reads:

```
radiusVec = np.logspace(0, 1, num=10)  # currently testing 10 radius values
sim_num = 0
conditions_per_process = int(
    len(radiusVec) / size
)  # currently only works for same number of conditions per process!
ss_vec_cur = np.zeros(conditions_per_process)
for idx in range(rank, len(radiusVec), conditions_per_process):
    curRadius = radiusVec[idx]
    # CODE TO SOLVE THE SYSTEM FOR THIS RADIUS VALUE
```

In the case of running 3 processes, this results in:

- Process 0 (root): assigned idx = 0, 3, 6, 9
- Process 1: assigned idx = 1, 4, 7
- Process 2: assigned idx = 2, 5, 8

During each run of the loop, there seems to effectively be an MPI barrier at  dolfin.assemble_mixed within the function, "init_petsc_matnest" inside of smart.solvers (line 274). This results in process 0 hanging during its fourth run of the loop, and the series of simulations never completes.

**Comment by emmetfrancis** [comment]
@jorgensd, with the updated version of the code, there still seems to be this same issue. I added some details in the above description, please let me know if anything is unclear.

**Comment by jorgensd** [comment]
> @jorgensd, with the updated version of the code, there still seems to be this same issue. I added some details in the above description, please let me know if anything is unclear.

I pushed some fixes to the MPI branch. It runs for me with 3 processes, let me know if it doesn't work for you.

**Comment by emmetfrancis** [comment]
The branch is functional now (with one change to cast the list of ss_vec arrays into a single 1D array), it looks like the execution was hanging because the correct mpi communicator was not used when writing the mesh to Paraview files.
